const U = (id, w = 600, h = 400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=82`;

export const menuCategories = [
  { id: 'pizzas', label: 'Pizzas', emoji: '🍕' },
  { id: 'pasta',  label: 'Pasta',  emoji: '🍝' },
  { id: 'wings',  label: 'Wings',  emoji: '🍗' },
  { id: 'drinks', label: 'Drinks', emoji: '🥤' },
];

export const menuItems = {
  pizzas: [
    {
      id: 'p1',
      name: 'Crustic Supreme',
      price: '$17.99',
      description: 'Loaded with pepperoni, Italian sausage, roasted bell peppers, caramelized onions, black olives, and rich house red sauce on our signature hand-stretched crust.',
      badge: 'Fan Favorite',
      badgeType: 'featured',
      tags: ['Bestseller', 'Meat Lover'],
      image: U('photo-1574071318508-1cdbab80d002'),
    },
    {
      id: 'p2',
      name: 'Honey Habanero',
      price: '$16.99',
      description: 'Fresh mozzarella, crispy bacon, sliced jalapeños, pickled red onion, finished with a generous hot honey drizzle and fresh chives.',
      badge: 'Spicy',
      badgeType: 'spicy',
      tags: ['Spicy', 'Sweet Heat'],
      image: U('photo-1565299624946-b28f40a0ae38'),
    },
    {
      id: 'p3',
      name: 'Margherita di Fuoco',
      price: '$14.99',
      description: 'San Marzano crushed tomato base, buffalo mozzarella torn by hand, fresh basil leaves, extra-virgin olive oil, and sea salt flakes.',
      badge: null,
      tags: ['Vegetarian', 'Classic'],
      image: U('photo-1513104890138-7c749659a591'),
    },
  ],
  pasta: [
    {
      id: 'pa1',
      name: 'Arrabbiata al Forno',
      price: '$13.99',
      description: 'Penne in a fiery San Marzano tomato sauce with garlic, crushed red pepper, and fresh parsley. Baked with a melted parmesan crust on top.',
      badge: null,
      tags: ['Vegetarian', 'Baked'],
      image: U('photo-1555949258-eb67b1ef0ceb'),
    },
    {
      id: 'pa2',
      name: 'Smoky Carbonara',
      price: '$15.99',
      description: 'Spaghetti in a silky egg and pecorino sauce with smoked pancetta, cracked black pepper, and a whisper of liquid smoke for depth.',
      badge: 'Signature',
      badgeType: 'featured',
      tags: ['Signature'],
      image: U('photo-1621996346565-e3dbc646d9a9'),
    },
    {
      id: 'pa3',
      name: 'Creamy Garlic Shrimp Linguine',
      price: '$17.99',
      description: 'Tender shrimp sautéed in garlic butter, tossed with linguine in a white wine cream sauce, topped with shaved parmesan and fresh lemon zest.',
      badge: null,
      tags: ['Seafood', 'Premium'],
      image: U('photo-1563379926898-05f4575a45d8'),
    },
  ],
  wings: [
    {
      id: 'w1',
      name: 'Garlic Parmesan Wings',
      price: '$12.99',
      description: 'Jumbo wings double-tossed in roasted garlic butter and aged parmesan. Served with house ranch dipping sauce and celery sticks.',
      badge: 'Most Ordered',
      badgeType: 'featured',
      tags: ['6 or 12 pcs'],
      image: U('photo-1527477396000-e27163b481c2'),
    },
    {
      id: 'w2',
      name: 'Crustic Fire Wings',
      price: '$13.99',
      description: 'Double-fried wings coated in our signature habanero-honey glaze with brown sugar and smoked paprika. Dangerously good.',
      badge: 'Hot',
      badgeType: 'spicy',
      tags: ['Spicy', 'Sweet'],
      image: U('photo-1567620832903-9fc6debc209f'),
    },
    {
      id: 'w3',
      name: 'Lemon Pepper Dry Rub',
      price: '$12.99',
      description: 'Golden crispy wings seasoned generously with a bold lemon pepper crust. Light, zesty, and absolutely addictive. Served with blue cheese dip.',
      badge: null,
      tags: ['Dry Rub', 'Crispy'],
      image: U('photo-1601050690597-df0568f70950'),
    },
  ],
  drinks: [
    {
      id: 'd1',
      name: 'Crustic House Lemonade',
      price: '$3.99',
      description: 'Fresh-squeezed lemonade with a hint of mint, served over ice. Available in original, strawberry, or mango.',
      badge: null,
      tags: ['House Made', 'Refreshing'],
      image: U('photo-1544145945-f90425340c7e'),
    },
    {
      id: 'd2',
      name: 'Italian Sodas',
      price: '$3.49',
      description: 'Sparkling water with your choice of house syrups — blood orange, blackberry, vanilla cream, or passion fruit.',
      badge: null,
      tags: ['Seasonal Flavors'],
      image: U('photo-1497534446932-c925b458314e'),
    },
    {
      id: 'd3',
      name: 'Fountain Drinks & Bottled Water',
      price: '$2.49',
      description: 'Pepsi, Diet Pepsi, Sierra Mist, Dr. Pepper, and Lipton Iced Tea. Still and sparkling water also available.',
      badge: null,
      tags: ['Free Refills'],
      image: U('photo-1437418747212-8d9709afab22'),
    },
  ],
};
